### ISSUE TITLE
SMILES chemistry.  Adding the ability to display alternating double and single lines for aromatic rings

### ISSUE THREAD

**Issue by OlgaRedozubova** [Mathpix/mathpix-markdown-it#103]
Aromaticity can be represented in one of two ways in a SMILES.

- In the Kekulé form, using alternating single and double bonds, with uppercase symbols for the atoms.
- An atomic symbol that begins with a lowercase letter is an aromatic atom, such as 'c' for aromatic carbon. When aromatic symbols are used, no bond symbols are needed.

A lowercase aromatic symbol is defined as an atom in the sp2 configuration in an aromatic or anti-aromatic ring system. For example:

<img width="438" alt="Снимок экрана 2020-11-12 в 08 43 04" src="https://user-images.githubusercontent.com/32493105/98905326-ec808380-24c3-11eb-84ef-8c1c69da6da8.png">

http://opensmiles.org/spec/open-smiles-3-input.html#4

In the SmilesDraw algorithm, aromatic rings are displayed using a ring or dashed lines (if there are bridge rings in the molecule):
<img width="426" alt="Снимок экрана 2020-11-12 в 08 50 58" src="https://user-images.githubusercontent.com/32493105/98905520-379a9680-24c4-11eb-98cd-316c38bfe928.png">

---

Need to add the ability to display aromatic rings (indicated by lowercase characters) using alternating double and single lines:
<img width="845" alt="Снимок экрана 2020-11-12 в 08 57 34" src="https://user-images.githubusercontent.com/32493105/98906082-2a31dc00-24c5-11eb-893c-eea7e9813976.png">

**Comment by OlgaRedozubova** [comment]
My current progress in this branch `dev/olga/Change-aromatic-ring-visualization`
I've created a test sample of use (comparing table) and deployed to `heroku`
https://smiles-test.herokuapp.com/
<img width="1482" alt="Снимок экрана 2020-11-12 в 17 40 36" src="https://user-images.githubusercontent.com/32493105/98961542-57ef4300-250e-11eb-998e-ef1a636666ec.png">

Here:
`Smiles Feature` - new ability to display aroma rings
`CDK` - mapping to https://www.simolecule.com/cdkdepict/depict.html
`Smiles` - before changes

@nicodjimenez @iammosespaulr Please let me know you think about this.

**Comment by iammosespaulr** [comment]
@OlgaRedozubova this is incredible! they seem to be super accurate! 🤩 

I only noticed one minor thing, and I don't know if these are due to your new changes, but
the double bond lines seem to be a bit longer than ideal
![image](https://user-images.githubusercontent.com/28682735/98963595-cf809a80-252d-11eb-9f09-57d8cc4ffeb9.png)
they seem to overlap some of the element names sometimes
![image](https://user-images.githubusercontent.com/28682735/98963711-f048f000-252d-11eb-9308-741fa513ed0a.png)

other than that, it's awesome!
also will there be an option to toggle between the two different modes ?

**Comment by OlgaRedozubova** [comment]
> the double bond lines seem to be a bit longer than ideal

@iammosespaulr Thank you for your observation. These lines are drawn this way in `SmileDrawer` by default.

I will change the `Short Bond Length` property to reduce them

>also will there be an option to toggle between the two different modes ?

Yes, I have already implemented this in the options:
1. Mode - (new feature). Used by default.
```
ringVisualization: 'default',                                                         
ringAromaticVisualization: 'default'
```
For smiles `$Cc1cc2c(cc1C)[n+]([O-])c(C#N)c(NS(=O)(=O)c3ccc4ccccc4c3)[n+]2[O-]`
<img width="265" alt="Снимок экрана 2020-11-12 в 18 39 27" src="https://user-images.githubusercontent.com/32493105/98968641-98eb5580-2516-11eb-9ec8-926692117528.png">

2. Mode - For drawing rings
```
ringVisualization: 'circle',
ringAromaticVisualization: 'dashed'
```
For smiles `$Cc1cc2c(cc1C)[n+]([O-])c(C#N)c(NS(=O)(=O)c3ccc4ccccc4c3)[n+]2[O-]`
<img width="257" alt="Снимок экрана 2020-11-12 в 18 39 36" src="https://user-images.githubusercontent.com/32493105/98968683-a7d20800-2516-11eb-87bd-32d81ea7404c.png">

**Comment by nicodjimenez** [comment]
Looks great! Cool web app!

**Comment by OlgaRedozubova** [comment]
I've merged it into master branch and updated package Mathpix-markdown-it v1.0.32

**Comment by nicodjimenez** [comment]
Ok then I'm closing this for now.
