### ISSUE TITLE
SMILES: show middle carbon?

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#109]
Input:

```
O=C=S
```

![image](https://user-images.githubusercontent.com/3152743/99299417-0b528300-2800-11eb-8694-05e6cbb5ff0b.png)

But MMD renders as:

![image](https://user-images.githubusercontent.com/3152743/99299438-12799100-2800-11eb-9d6f-9b9a6bc9b4de.png)

What do you think @OlgaRedozubova and @iammosespaulr ?

**Comment by iammosespaulr** [comment]
Oh no
![image](https://user-images.githubusercontent.com/28682735/99299798-c36c4400-2871-11eb-9fd9-9fec3333aff9.png)
I guess the "dot" is being omitted, it should render the middle carbon or a dot atleast
The current depiction is kinda confusing
<img width="441" alt="image" src="https://user-images.githubusercontent.com/28682735/99299975-029a9500-2872-11eb-85dd-5f91db385d4f.png">

we could make the rule simple, 
if single carbon in the molecule, display "C"

**Comment by OlgaRedozubova** [comment]
I've fixed it and updated mmd v1.0.34
<img width="1466" alt="Снимок экрана 2020-11-19 в 11 06 03" src="https://user-images.githubusercontent.com/32493105/99645039-5f0ad980-2a57-11eb-9cb9-0fb618fb2744.png">
