### ISSUE TITLE
SMILES rendering bug

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#110]
This SMILES:

```
FCl(=O)(=O)=O
```

renders:

![image](https://user-images.githubusercontent.com/3152743/99459335-ca7f6a80-28e2-11eb-9e3b-3b200fcfcdf6.png)

**Comment by OlgaRedozubova** [comment]
I've fixed it and updated mmd v1.0.34
<img width="1176" alt="Снимок экрана 2020-11-19 в 11 01 47" src="https://user-images.githubusercontent.com/32493105/99644570-cb390d80-2a56-11eb-9ebc-79049a777552.png">
