### ISSUE TITLE
When I use mathpix-markdown-it to parse Chinese, the typesetting is abnormal.

### ISSUE THREAD

**Issue by tanjie123** [Mathpix/mathpix-markdown-it#124]
![2](https://user-images.githubusercontent.com/18720144/103887699-7ba1c480-511e-11eb-852b-1d2816d0f066.png)

**Comment by nicodjimenez** [comment]
Hi thanks for posting! if you don't mind, can you also post the text that renders poorly? That will help us reproduce this issue.

**Comment by OlgaRedozubova** [comment]
@tanjie123 It's working. 
You can test it this https://htmlpreview.github.io/?https://github.com/Mathpix/mathpix-markdown-it/blob/master/examples/html/input-mmd-to-html.html

```
text = 中国尔子,你子国

MathJax = $\text { 中国尔子,你子国 }$
```

<img width="484" alt="Снимок экрана 2021-01-15 в 15 27 19" src="https://user-images.githubusercontent.com/32493105/104740830-1585f480-5751-11eb-8903-3d6943bd5230.png">

**Comment by montanaflynn** [comment]
@OlgaRedozubova this appears to be related to the snip app rather than this library. It appears the spacing is too narrow between characters?

@tanjie123 can I ask what operating system you're using?

**Comment by OlgaRedozubova** [comment]
The problem occurs in the `MathJax` package for node applications. There are no such problems for the browser.
`MathJax` issues:
https://github.com/mathjax/MathJax-demos-node/issues/14
https://github.com/mathjax/MathJax-demos-node/issues/29


Proposed solution: https://github.com/mathjax/MathJax/issues/2329#issuecomment-586371301
