### ISSUE TITLE
Fix broken \author{...} rendering when the author list has block mode delimiters

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#142]
Currently:

```
\author{
Author 1 \( x \) \\ Author 2 \[ x \]
}
```

yields this broken rendering:

![image](https://user-images.githubusercontent.com/3152743/112929332-116d4000-90cd-11eb-882d-f7c895318ad4.png)

whereas in LaTeX:

![image](https://user-images.githubusercontent.com/3152743/112929361-20ec8900-90cd-11eb-8566-19d7fccbda37.png)
![image](https://user-images.githubusercontent.com/3152743/112929371-26e26a00-90cd-11eb-9501-f9db7123e659.png)

**Comment by OlgaRedozubova** [comment]
I've fixed it in `mathpix-markdown-it@1.0.52` 

<img width="862" alt="Снимок экрана 2021-04-01 в 09 58 57" src="https://user-images.githubusercontent.com/32493105/113255786-e8b59800-92d0-11eb-9d52-55c84b8bee32.png">
