### ISSUE TITLE
Support \wideparen { ... }

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#147]
Is this supported by MathJax?

**Comment by OlgaRedozubova** [comment]
MathJax does not support the `wideparen` command.
Instead, MathJax has the command `overparen`. 
`$\overparen{ABC}$`

But we can add a macro to support the `wideparen` command:
<img width="525" alt="Снимок экрана 2021-04-20 в 13 49 37" src="https://user-images.githubusercontent.com/32493105/115384469-bf0cd400-a1df-11eb-8a95-4abb63594a7a.png">

@nicodjimenez Please let me know what do you think about it.
