### ISSUE TITLE
Smiles rendering does not support "R" letter (functional groups)

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#149]
Maybe this is easy so solve?

**Comment by OlgaRedozubova** [comment]
"R" letter is rendered for smiles

`<smiles>OC(=O)C([R])N</smiles>`
`<smiles>[R]C1C([R])C([R])C([R])1</smiles>`
`<smiles>OC[R]N</smiles>`
<img width="829" alt="Снимок экрана 2021-04-27 в 06 47 51" src="https://user-images.githubusercontent.com/32493105/116182708-68deea00-a725-11eb-9f61-6e63f26ec12f.png">

@nicodjimenez Please share with me a smiles that is rendered incorrectly

**Comment by nicodjimenez** [comment]
Ah you need the [] that's why :)
