### ISSUE TITLE
Rendering of `\pounds` does not work

### ISSUE THREAD

**Issue by dlrac** [Mathpix/mathpix-markdown-it#168]
Related issue: https://github.com/Mathpix/mathpix/issues/1630

Basically rendering `\pounds` does not work, error is undefined control sequence.

**Comment by OlgaRedozubova** [comment]
I added it in the [mathpix-markdown-it@1.0.65](https://www.npmjs.com/package/mathpix-markdown-it)
<img width="670" alt="Screen Shot 2021-09-02 at 17 37 42" src="https://user-images.githubusercontent.com/32493105/131863714-c8aa29f0-c897-4a40-b9f5-998a94ae4826.png">
