### ISSUE TITLE
\& inside tabular environments not working

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#21]
![image](https://user-images.githubusercontent.com/3152743/72862952-c31c1000-3c83-11ea-8326-b1ca1740b337.png)

This is what we expect to see with this Latex:

![image](https://user-images.githubusercontent.com/3152743/72862979-d29b5900-3c83-11ea-9723-5cd3d5005bed.png)

**Comment by OlgaRedozubova** [comment]
@nicodjimenez I've fixed it and merged into master branch.
![screenshot-admin2 zenpix io-2020 01 31-12_04_41](https://user-images.githubusercontent.com/32493105/73531008-44149d80-4422-11ea-88c7-1246ec33dfc9.png)

**Comment by nicodjimenez** [comment]
Sweet!
