### ISSUE TITLE
Render SVG+XML in base64 as Img tag

### ISSUE THREAD

**Issue by vladtimss** [Mathpix/mathpix-markdown-it#210]
In markdown-it i can override link validator to use svg+xml data type for img tag

see 23 code row https://github.com/markdown-it/markdown-it/blob/064d602c6890715277978af810a903ab014efc73/lib/index.js

standard markdown-it gives only gif | png | jpeg | webp types. i need add jpg and svg+xml

like this 
```
mdit.validateLink = (url: string) => {
    const BAD_PROTO_RE = /^(vbscript|javascript|file|data):/;
    const GOOD_DATA_RE = /^data:image\/(gif|png|jpeg|jpg|webp|svg\+xml);/;
    const str = url.trim().toLowerCase();
    return BAD_PROTO_RE.test(str) ? GOOD_DATA_RE.test(str) : true;
};
```

i want render string like this one
`![chart.svg](data:image/svg+xml;base64, ...base64....`

how can i do it?

**Comment by OlgaRedozubova** [comment]
@vladtimss This is a `markdown-it` security limitation, but you can find the answer to your question in the `markdown-it` repository:
https://github.com/markdown-it/markdown-it/pull/769

**Comment by vladtimss** [comment]
@OlgaRedozubova thanks!

Yes, i created my own function and get my needs, but in markdown-it.

I would like to do it in mathpix-markdown-it. Is there any cases to get it?

In markdown-it i create instance of it, then i can override method names validatLink, but i couldn't find this method in mathpix-markdown-it

**Comment by OlgaRedozubova** [comment]
@vladtimss I've just updated mathpix-markdown-it@1.0.80

In new version I added `validateLink` parameter to override md link validator. (User request #210)

```js
const html = markdownToHTML(mmdString, {
 validateLink: (url: string) => {
    const BAD_PROTO_RE = /^(vbscript|javascript|file|data):/;
    const GOOD_DATA_RE = /^data:image\/(gif|png|jpeg|jpg|webp|svg\+xml);/;
    const str = url.trim().toLowerCase();
    return BAD_PROTO_RE.test(str) ? GOOD_DATA_RE.test(str) : true;
  }
});
```
 
<img width="907" alt="Screen Shot 2022-11-28 at 09 32 17" src="https://user-images.githubusercontent.com/32493105/204233614-7512166e-d09d-45c5-aecf-f0472059d13a.png">

**Comment by vladtimss** [comment]
@OlgaRedozubova oh!! Here too many many thanks!!!!
