### ISSUE TITLE
Latex Renderer Creates a window event listener which makes all the link non-clickable

### ISSUE THREAD

**Issue by sahilsakhiya11** [Mathpix/mathpix-markdown-it#225]
I am using mathpix for converting math images into math equation and converting drawing into math equation. 

I am using mathpix-markdown-it library with React. 
I want to remove that global event listener so all my links in my single page application remains clickable. 

![image](https://user-images.githubusercontent.com/37842013/215802251-e85dcc6d-3d04-47be-9c0d-1552d1b44779.png)

this is the function from the library makes it all the links non-clickable.

![image](https://user-images.githubusercontent.com/37842013/215802536-89530612-4422-4d63-a632-7d9c7bc5bcf6.png)

**Comment by OlgaRedozubova** [comment]
@sahilsakhiya11 This function is used to scroll the preview to the middle of the screen when clicking on a reference related to equation.
You can disable this behavior by passing `true` to the function
`MathpixMarkdownModel.loadMathJax(true)`
Or if you are using a component:
```js
      <MathpixLoader notScrolling={true}>
          <MathpixMarkdown text="\\(ax^2 + bx + c = 0\\)"/>
          <MathpixMarkdown text="$x = \frac { - b \pm \sqrt { b ^ { 2 } - 4 a c } } { 2 a }$"/>
          ...
      </MathpixLoader>
```

**Comment by sahilsakhiya11** [comment]
@OlgaRedozubova Thank you, it works.
