### ISSUE TITLE
Problem with \[ and \( in latex

### ISSUE THREAD

**Issue by sahilsakhiya11** [Mathpix/mathpix-markdown-it#239]
Hey, I am using mathpix markdown it with react. 

and getting an undefined sequence error with \[ and \( 

![image](https://user-images.githubusercontent.com/37842013/231483025-5c78d224-4092-4983-825a-2ea213b9c3c0.png)

can you please help me with it, how can i solve it. I am using this library to convert latex into images and then rendering into quill(wysiwyg library). 

thank you in advance.

**Comment by OlgaRedozubova** [comment]
@sahilsakhiya11 Hey. 
This error means invalid syntax inside math. You don't need to escape the shackles inside the math expression.

For example:
Wrong syntax:
 
<img width="1000" alt="Screen Shot 2023-04-13 at 08 23 19" src="https://user-images.githubusercontent.com/32493105/231661941-87c1d306-e231-4bd8-90b6-78442cee2f9e.png">

Instead, just use `[`/`)` or specify `\left(` `\right)`:

 
<img width="891" alt="Screen Shot 2023-04-13 at 08 25 25" src="https://user-images.githubusercontent.com/32493105/231662330-27542d9f-57b9-4a68-a6d8-e4e9f7c14db4.png">


Also, please share mmd which causes this error.

**Comment by sahilsakhiya11** [comment]
Thank you it is useful. 
Closing it.
