### ISSUE TITLE
Load/include a custom language module to avoid error in markdown highlight

### ISSUE THREAD

**Issue by vladtimss** [Mathpix/mathpix-markdown-it#252]
Hi! 

I want load the 'jldoctest' custom language module for using in markdown block code to higlight, but got err like this 

> Could not find the language 'jldoctest', did you forget to load/include a language module? 

i tried to do this case

```
```jldoctest
a = 1
b = 2
a + b

# output

3
`
```

then get error described above

And additional issue - how avoid same errors in console? Seems, it would be better to avoid such errors and don't highlight.

**Comment by vladtimss** [comment]
@OlgaRedozubova hey :-)
Do you have some advices how fix it?

**Comment by OlgaRedozubova** [comment]
@vladtimss It's fixed in [mathpix-markdown-it@1.2.5](https://github.com/Mathpix/mathpix-markdown-it/pull/259)

**Comment by vladtimss** [comment]
@OlgaRedozubova many thanks. But we have one more issue with highlight. If start write language name with ``` syntax to highlight code, on each written char i will get error in console. Seems, it would be good way to avoid it. I applied demo of this problem.

Perhaps, we can check markup with trying detect language and if the attempt is failed we should apply autohighlight. Or there is some more way to solve it.

https://github.com/Mathpix/mathpix-markdown-it/assets/117174291/b24152ab-99aa-4ec3-afdd-fd46f27c56fc

**Comment by OlgaRedozubova** [comment]
@vladtimss Thank you for your comment. This has been fixed in [mathpix-markdown-it@1.2.6](https://github.com/Mathpix/mathpix-markdown-it/pull/263)
