### ISSUE TITLE
Uncaught ReferenceError: global is not defined when using Vite + React + Typescript

### ISSUE THREAD

**Issue by Niko030303** [Mathpix/mathpix-markdown-it#274]
![image](https://github.com/Mathpix/mathpix-markdown-it/assets/82041918/2a370eb9-1802-4bd4-b41a-6ddd747f4f3f)

![image](https://github.com/Mathpix/mathpix-markdown-it/assets/82041918/2e9a8f68-22ce-4df5-8a45-07869f489b54)

**Comment by OlgaRedozubova** [comment]
Just to add 
```
  define: {
    global: {},
  },
```

into `defineConfig`

https://stackoverflow.com/questions/72114775/vite-global-is-not-defined

**Comment by Niko030303** [comment]
it worked, i use the original method, thank you!
