### ISSUE TITLE
Don't img tags support object URL？

### ISSUE THREAD

**Issue by nicolas-tesla-x** [Mathpix/mathpix-markdown-it#314]
As shown, when I set the src attribute of img to Object URL, the src attribute is lost

![image](https://github.com/Mathpix/mathpix-markdown-it/assets/25948904/d3b0e3d1-9af2-4cce-b4c0-c72e13be8720)

**Comment by OlgaRedozubova** [comment]
@nicolas-tesla-x `blob:html` is considered an invalid URL scheme and does not pass the Sanitize check.

```
  // URL schemes we permit
  allowedSchemes: ['http', 'https', 'ftp', 'mailto'],
```

For this to work, need to disable the Sanitize check.
This can be done by setting `htmlSanitize: false`

`window.markdownToHTML(s, {htmlTags: true, htmlSanitize: false}) `

<img width="1379" alt="Screenshot 2024-03-21 at 09 58 28" src="https://github.com/Mathpix/mathpix-markdown-it/assets/32493105/4b61ef88-ad72-4382-ab72-45fbc2dd9467">

**Comment by nicolas-tesla-x** [comment]
> @nicolas-tesla-x `blob:html` is considered an invalid URL scheme and does not pass the Sanitize check.
> 
> ```
>   // URL schemes we permit
>   allowedSchemes: ['http', 'https', 'ftp', 'mailto'],
> ```
> 
> For this to work, need to disable the Sanitize check. This can be done by setting `htmlSanitize: false`
> 
> `window.markdownToHTML(s, {htmlTags: true, htmlSanitize: false}) `
> 
> <img alt="Screenshot 2024-03-21 at 09 58 28" width="1379" src="https://private-user-images.githubusercontent.com/32493105/315201260-4b61ef88-ad72-4382-ab72-45fbc2dd9467.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDA2NDcsIm5iZiI6MTcxMTEwMDM0NywicGF0aCI6Ii8zMjQ5MzEwNS8zMTUyMDEyNjAtNGI2MWVmODgtYWQ3Mi00MzgyLWFiNzItNDVmYmMyZGQ5NDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA5MzkwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5MWI1NjkwODljY2EwNGMyYTcwOWMxZGUyMGFlYmVkOGRiNzQwMjJjZjIwYjg0ZDA4ZTdhODg4MGMzODhlNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1cKrqgVcSAHcIOerumZ5Yf_DYOYSLIeGDOQNLYgvuxY">

thank you! It works!
