### ISSUE TITLE
Brace matching error in caption

### ISSUE THREAD

**Issue by peterzjx** [Mathpix/mathpix-markdown-it#317]
Braces seems to match greedily in captions.
Reproducible example:
```
\begin{table}
\caption{test \textbf{bold} test}
\end{table}
```
shows up as 
```
test}
Table 1: test \textbf{bold
```

**Comment by OlgaRedozubova** [comment]
@peterzjx Fixed:
<img width="1168" alt="Screenshot 2024-09-12 at 13 56 09" src="https://github.com/user-attachments/assets/074c320b-c627-4a64-ba95-7e2cc2fade4f">
