### ISSUE TITLE
Licence Information

### ISSUE THREAD

**Issue by AbhishekChugh** [Mathpix/mathpix-markdown-it#33]
Hello!
Thanks a ton for making this valuable library open-source. I am sure that the academic community will greatly benefit from this. Do you mind adding a license to this repo?

**Comment by OlgaRedozubova** [comment]
Hello @AbhishekChugh 
We added MIT license https://github.com/Mathpix/mathpix-markdown-it/blob/master/LICENSE

**Comment by AbhishekChugh** [comment]
Thanks guys! This new language will be quite useful.
