### ISSUE TITLE
Underline using html tag "<u>" does not support?

### ISSUE THREAD

**Issue by vladtimss** [Mathpix/mathpix-markdown-it#336]
Hi! Thanks for your good project.

I'd like to add underline on some text via "<u>" tag like this  `<u>some text</u>`

Does it possible with any way?

**Comment by vladtimss** [comment]
@OlgaRedozubova please help

**Comment by OlgaRedozubova** [comment]
@vladtimss For some reason, the HTML tag `<u>` does not pass the Sanitize check and is removed.
I'm researching this.
For a quick solution, you can simply disable the cleaning of unresolved tags using the `htmlSanitize: false` option.

<img width="654" alt="Screenshot 2024-07-10 at 16 00 39" src="https://github.com/Mathpix/mathpix-markdown-it/assets/32493105/8b1b3b79-8a78-48e7-a9f6-1a8ea520c096">

**Comment by vladtimss** [comment]
> @vladtimss For some reason, the HTML tag `<u>` does not pass the Sanitize check and is removed. I'm researching this. For a quick solution, you can simply disable the cleaning of unresolved tags using the `htmlSanitize: false` option.
> 
> <img alt="Screenshot 2024-07-10 at 16 00 39" width="654" src="https://private-user-images.githubusercontent.com/32493105/347411431-8b1b3b79-8a78-48e7-a9f6-1a8ea520c096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyOTE5MzEsIm5iZiI6MTcyMTI5MTYzMSwicGF0aCI6Ii8zMjQ5MzEwNS8zNDc0MTE0MzEtOGIxYjNiNzktOGE3OC00OGU3LWE5ZjYtMWE4ZWE1MjBjMDk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA4MzM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMzRkNTg5NmNhMWY3Njc3MTFlMzFlYWUwODRmZjI4YjZkZjhhOGI0ZjhlNDA4YTRhYzJkMTg0NzIwMDczZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DWA4PA89ibgVJJUL9FdMsgVxRtQyx6TF4bU3if7VkFQ">

hmm, thanks for your answer. 
But i'm confused of disabling sanitizer due to security. seems it can be not. Seems it may not be safe... what do you think?
Perhaps i should try disable sanitize and use some another sanitizer before pass markup to mathpix?
