### ISSUE TITLE
<mjx-container ...> ... </mjx-container> should not be included in svg output

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#43]
The svg format should start with `<svg ...>` and end with `</svg>`.

**Comment by OlgaRedozubova** [comment]
@nicodjimenez I've fixed it.
![ezgif com-video-to-gif (61)](https://user-images.githubusercontent.com/32493105/75354834-47cb0100-58b6-11ea-9fd7-a4f91d038a8e.gif)
