### ISSUE TITLE
Table bug (?)

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#68]
With PDFLatex, this string:

```
\begin{tabular}{|c|c|c|c|c|c|}\hline \multirow{2}{*} {} & \multicolumn{2}{|c|} { Latency \( (\mathrm{s}) \)} & \multicolumn{2}{|c|} { Message Sizes \( (\mathrm{MB}) \)} & \multirow{2}{*} { Accuracy \( \% \)} \\ \cline { 2 - 5 } & offline & online & offline & online & \\ \hline ReLU/CNN/MNIST (Figure 12) & 3.58 & 5.74 & 20.9 & 636.6 & 99.0 \\ \hline ReLU/CNN/CIFAR-10 (Figure 13) & 472 & 72 & 3046 & 6226 & 81.61 \\ \hline Sigmoidal/LSTM/PTB (Figure 14) & 13.9 & 4.39 & 86.7 & 474 & cross-entropy loss:4.79 \\ \hline\end{tabular}
```

renders:

![image](https://user-images.githubusercontent.com/3152743/77586490-8a76fd80-6ea3-11ea-9074-f5657fe71c44.png)

However, with mathpix-markdown-it, I'm getting:

![image](https://user-images.githubusercontent.com/3152743/77586526-96fb5600-6ea3-11ea-89f0-32b05d847365.png)

**Comment by OlgaRedozubova** [comment]
@nicodjimenez I've fixed it
![screenshot-admin2 zenpix io-2020 03 27-17_26_30](https://user-images.githubusercontent.com/32493105/77772153-5bea5580-7050-11ea-8f9d-3add7e5d8949.png)
