### ISSUE TITLE
Latex command:  "" not working

### ISSUE THREAD

**Issue by EliasSchlatter** [Mathpix/mathpix-markdown-it#72]
this latex command will break the rendering: "C = \left\{-\frac{1}{2}, \sqrt{2} \right\} \not \subset M"

if the  "\not" is removed the code will work. is there a workaround or can you guys fix it?

Best,
Elias

**Comment by OlgaRedozubova** [comment]
@EliasSchlatter I've fixed it
![screenshot-staging-snip mathpix com-2020 04 15-18_55_22](https://user-images.githubusercontent.com/32493105/79359280-13d19b00-7f4b-11ea-8a21-d7706327b8cb.png)

**Comment by nicodjimenez** [comment]
Thanks for creating the issue @EliasSchlatter ! Closing this as this does appear fixed.

**Comment by EliasSchlatter** [comment]
Awesome, thanks for the fast fix!

Best,
Elias
