### ISSUE TITLE
Bug converting roots to asciimath

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#73]
This latex:

`\frac{\sqrt[4]{32 z^{6} y^{3}}}{\sqrt[4]{2 z^{2} y^{11}}}` 

gets converted into asciimath: 

`(root(32z^(6)y^(3))(4))/(root(2z^(2)y^(11))(4))`

Instead, this should be the correct asciimath:

`root(4)(32x^(6)y^(3))/(root(4)(2z^(2)y^(11)))`

**Comment by OlgaRedozubova** [comment]
@nicodjimenez I've fixed it
```
parsed=> [
  {
    type: 'asciimath',
    value: '(root(4)(32z^(6)y^(3)))/(root(4)(2z^(2)y^(11)))'
  }
]
```

**Comment by nicodjimenez** [comment]
Thanks!
