### ISSUE TITLE
Theorem environments?

### ISSUE THREAD

**Issue by leotrs** [Mathpix/mathpix-markdown-it#77]
It seems like the current version does not support theorem (and theorem-like) environments. Is this feature planned for the future? Thanks!

**Comment by nicodjimenez** [comment]
Hi @leotrs thanks for letting us know about this. 

Can you be more specific? You mean like shortcuts for "Theorem" and "Lemma"?

**Comment by leotrs** [comment]
I mean the equivalent of `\begin{theorem}... \end{theorem}`, `\begin{lemma}... \end{lemma}`, `\begin{proof}... \end{proof}`, etc.

**Comment by leotrs** [comment]
I've recently seen a lot of movement in this repo, which is exciting! I love the mathpix website. Is there a chance to have this issue looked at again? Thanks.

**Comment by dualer** [comment]
I agree with leotrs, this function is necessary.

**Comment by bkaplowitz** [comment]
I agree as well. This would be great to add.

**Comment by nicodjimenez** [comment]
Ok we will finally start working on this asap! It's long overdue. 

Great overview of theorems and proofs environments at:

https://www.overleaf.com/learn/latex/Theorems_and_proofs

**Comment by ykolodnitskiy** [comment]
@leotrs @dualer @bkaplowitz 

We've added theorems support! You can find docs here: https://github.com/Mathpix/mathpix-markdown-it/blob/master/doc/theorems.md
