### ISSUE TITLE
Support for \textit{\textbf{...}} and \textbf{\textit{...}}

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#78]
This is how to make bold + italics font in PDFLatex, but it doesn't work in mathpix-markdown-it:

![image](https://user-images.githubusercontent.com/3152743/82374703-45b7a080-99d4-11ea-9ee4-b7a62d8a4c0c.png)

It would be great to support this.

**Comment by nicodjimenez** [comment]
Works great, thanks!

**Comment by khdarii** [comment]
@OlgaRedozubova I want to inform you of a mistake by using` \textbf` with `\textit` in the math mode.
<img width="405" alt="image" src="https://user-images.githubusercontent.com/48454742/113170416-35f12580-924f-11eb-9b13-9964356b4518.png">
