### ISSUE TITLE
">" symbol breaking math parser

### ISSUE THREAD

**Issue by nicodjimenez** [Mathpix/mathpix-markdown-it#85]
![image](https://user-images.githubusercontent.com/3152743/90442127-00684500-e08f-11ea-81c7-f702de46570d.png)

![image](https://user-images.githubusercontent.com/3152743/90442150-06f6bc80-e08f-11ea-8fe5-36a51d3431ef.png)

**Comment by OlgaRedozubova** [comment]
@nicodjimenez I've fixed it.
![screenshot-admin2 zenpix io-2020 08 19-09_30_18](https://user-images.githubusercontent.com/32493105/90600397-27de1f80-e1ff-11ea-8318-ad1f103b3e39.png)
